In [31]:
import os
from enum import Enum
from typing import Dict, List, Optional, Tuple, Union

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from IPython.display import clear_output
from tqdm.auto import tqdm

from utils.datasets import (
    ARTIFACTS_FOLDER,
    ROOT_FOLDER,
    STATIC_FEATURES,
    HydroFiles,
    HydroStaticFeaturesFiles,
    MeteoSeriesFeaturesFiles,
)
from utils.types import TimeRange

%matplotlib inline
os.chdir(ROOT_FOLDER)

In [32]:
import polars as pl
import dask.dataframe as dd
from pathlib import Path

In [33]:
PATH_MERGED_DATASETS = ARTIFACTS_FOLDER / 'merged_datasets'
train_df = pl.read_csv(PATH_MERGED_DATASETS / "train_file_ids.csv")
file_ids = train_df["file_id"].to_list()
file_ids[:5]

[8230, 8233, 8241, 8249, 8251]

In [34]:
paths = [PATH_MERGED_DATASETS / (str(file_id) + '.parquet') for file_id in file_ids]
paths[0]

PosixPath('/home/khuzin/Projects/2025-Project-188/data/artifacts/merged_datasets/8230.parquet')

In [39]:
ddf = dd.read_parquet(paths)
ddf.head()

,date,prcp,t_max,t_mean,t_min,q_mm_day,lvl_sm,gauge_id
0,2008-01-01,0.184543,-36.468083,-38.569561,-40.554178,0.047203,131.0,1151
1,2008-01-02,0.420088,-31.148393,-34.593115,-37.576221,0.045645,132.0,1151
2,2008-01-03,2.527887,-29.196286,-29.795872,-31.042251,0.044086,132.0,1151
3,2008-01-04,1.288245,-29.178316,-31.346584,-33.175628,0.042750,132.0,1151
4,2008-01-05,1.096579,-30.258844,-31.564057,-33.546148,0.041192,132.0,1151

In [41]:
ddf[["prcp", "gauge_id"]].groupby("gauge_id").mean().head()

              prcp
gauge_id
8361      2.850941
76671     3.963221
76690     4.919446
70410     5.432813
12043     2.133727